10 PRINT "DISTANCIA PERCORRIDA EM KM:"
20 INPUT DISTANCIA
30 PRINT "COMBUSTIVEL GASTO (LITROS):"
40 INPUT COMBUSTIVEL
50 LET CONSUMO = DISTANCIA / COMBUSTIVEL
60 PRINT "CONSUMO MEDIO: "; CONSUMO; " KM/L"
70 END
